//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan
    {
        public int LoanId { get; set; }
        public Nullable<long> LoanAmount { get; set; }
        public Nullable<System.DateTime> Due_Date { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<long> Income { get; set; }
        public string LoanType { get; set; }
        public string PanNo { get; set; }
        public string AadharNo { get; set; }
        public string BankAcc { get; set; }
        public string UserId { get; set; }
        public Nullable<int> LoanAgency_AdminId { get; set; }
        public Nullable<int> VAgent { get; set; }
        public Nullable<int> AppAgencyAgent { get; set; }
        public Nullable<int> PickupAgent { get; set; }
        public Nullable<int> LegalAgent { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual Agent Agent1 { get; set; }
        public virtual Agent Agent2 { get; set; }
        public virtual Agent Agent3 { get; set; }
        public virtual Agent Agent4 { get; set; }
        public virtual User User { get; set; }
    }
}
