//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int RequestId { get; set; }
        public string Issue { get; set; }
        public string Descrip { get; set; }
        public Nullable<System.DateTime> DateTicket { get; set; }
        public string Resolution { get; set; }
        public string UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
